<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray"><?php echo $this->translate('You are here:'); ?> </div>
    <li>
        <a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
    </li>
</ul>
<div class="page-header">

    <div class="row">
        <!-- Page header, center on small screens -->
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
            <i class="fa fa-dashboard page-header-icon">                
            </i>&nbsp;&nbsp;<?php echo $this->translate("Dashboard"); ?>
        </h1>
    </div>
</div> 
<!-- / .page-header -->