<?php
/**
 * @var \Zend\Form\Form $this
 * @var \Account\Form\AccountForm $form
 */
$form = $this->form;
$form->setAttribute(
	 'action',
		 $this->url(
			  'account',
				  [
					  'controller' => 'index',
					  'action' => 'add'
				  ]
		 )
);
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
	<label for="inputUsername" class="col-sm-2 control-label">Username</label>

	<div class="col-sm-10">
		<?php echo $this->formRow($form->get('username')); ?>
	</div>
</div>

<div class="form-group">
	<label for="inputPassword" class="col-sm-2 control-label">Password</label>

	<div class="col-sm-10">
		<?php echo $this->formRow($form->get('password')); ?>
	</div>
</div>

<div class="form-group">
	<label for="inputSalt" class="col-sm-2 control-label">Salt</label>

	<div class="col-sm-10">
		<?php echo $this->formRow($form->get('salt')); ?>
	</div>
</div>

<div class="form-group">
	<label for="inputEmail" class="col-sm-2 control-label">E-Mail</label>

	<div class="col-sm-10">
		<?php echo $this->formRow($form->get('email')); ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?php echo $this->formRow($form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>

