<?php
/**
 * @var \ORM\Entity\Account $account
 */
?>
<div>
	<div>
		<div>
			<div>
				<h3>Users</h3>
			</div>
			<div>
				<a href="<?php echo $this->url('account', array('action' => 'add')); ?>">Add User</a>

				<?php if (isset($accounts)) : ?>
					<table>
						<thead>
						<tr>
							<th>Id</th>
							<th>Full name</th>
							<th></th>
						</tr>
						</thead>
						<?php foreach ($accounts as $account): ?>
							<tbody>
							<tr>
								<td><?php echo $account->getId(); ?></td>
								<td><?php echo $account->getUsername(); ?></td>
								<td>
									<a href="<?php echo $this->url('account', array('action' => 'edit', 'id' => $account->getId())); ?>">Edit</a>
									|
									<a href="<?php echo $this->url('account', array('action' => 'delete', 'id' => $account->getId())); ?>">Delete</a>
								</td>
							</tr>
							</tbody>
						<?php endforeach; ?>
					</table>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
