<?php
/**
 * 
 */
?>
<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">
        <?php echo $this->translate('You are here:'); ?> 
    </div>
    <li>       
        <a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
    </li>
    <li>
        <a href="<?php echo $this->url('post/post_category'); ?>"><?php echo $this->translate('Categories'); ?></a>
    </li>
    <?php if (null == $keyword): ?>
        <li class="active">
            <?php echo $this->translate('Edit category'); ?>
        </li> 

    <?php else: ?>
        <li>
            <a href="<?php echo $this->url('post/post_category_edit', ['id' => $taxid]); ?>"><?php echo $this->translate('Edit category'); ?></a>
        </li>
        <li>
            <a href="<?php echo $this->url('post/post_category_edit', ['id' => $taxid]); ?>?keyword=<?php echo $keyword; ?>"><?php echo $this->translate('Keyword'); ?></a>
        </li>
        <li class="active">
            <?php echo $keyword; ?>
        </li> 
    <?php endif; ?>
</ul>
<div class="page-header">

    <div class="row">
        <div class="col-xs-6">            
            <h1 class="text-center text-left-sm">
                <i class="fa fa-sitemap page-header-icon"> </i>
                &nbsp;
                <?php echo $this->translate("Categories"); ?>        
                <?php echo $this->translate('or'); ?>
                <a href="<?php echo $this->url('post/post_category_add'); ?>"><?php echo $this->translate('Add New'); ?></a>
            </h1>
        </div>
        <div class="col-xs-6">
            <div class="pull-right" style="width: 60%">        
                <?php
                $formsearch->setAttribute('action', $this->url('post/post_category_edit', ['id' => $taxid]));
                $formsearch->prepare();
                $search = $formsearch->get('search');
                $search->get('keyword')->setattributes([
                    'class' => 'form-control',
                    'placeholder' => $this->translate('Search category')
                ]);
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($formsearch); ?>               
                <div class="input-group input-group-sm">
                    <input type="hidden" name="search[id]" value="<?php echo $taxid; ?>"/>
                    <?php echo $this->formHidden($formsearch->get('security')); ?>
                    <?php echo $this->formRow($search->get('keyword')); ?>
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">
                            <span class="fa fa-search"></span>
                        </button>
                    </span>
                </div>               
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div> 
<div class="row">
    <div class="col-sm-4">
        <?php
        $form->setAttribute('action', $this->url('post/post_category_edit'));
        $form->prepare();
        $tax = $form->get("tax");

        $parent = [];

        function line($c)
        {
            $d = '';
            for ($l = 0; $l < $c; $l++) {
                $d .= '- ';
            }
            return $d;
        }

        foreach ($taxparent as $p):

            if ($p->getLvl() === 0) {
                $parent[$p->getId()] = $p->getName();
            } else {
                $parent[$p->getId()] = html_entity_decode(line($p->getLvl()) . $p->getName());
            }
        endforeach;

        $tax->get('parent')->setOptions(['value_options' => $parent]);
        ?>

        <div class="panel">
            <div class="panel-heading">
                <span class="panel-title">
                    <i class="panel-title-icon fa  fa-edit"></i>
                    <?php echo $this->translate('Edit Category'); ?>                   
                </span>
            </div>
            <div class="panel-body">                
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <label for="inputName" class="control-label">
                        <?php echo $this->translate('Title'); ?>
                    </label>
                    <?php echo $this->formHidden($form->get('security')); ?>
                    <?php echo $this->formHidden($tax->get('id')); ?>
                    <?php echo $this->formRow($tax->get('name')); ?>
                </div>
                <div class="form-group">
                    <label for="inputSlug" class="control-label">
                        <?php echo $this->translate('Slug'); ?>
                    </label>
                    <?php echo $this->formRow($tax->get('slug')); ?>
                </div>
                <div class="form-group">
                    <label for="inputParent" class="control-label">
                        <?php echo $this->translate('Parent'); ?>
                    </label>
                    <?php echo $this->formRow($tax->get('parent')); ?>
                </div>
                <div class="form-group">
                    <label for="inputStaus" class="control-label">
                        <?php echo $this->translate('Status'); ?>
                    </label>
                    <?php echo $this->formRow($tax->get('status')); ?>
                </div>
                <div class="form-group">
                    <label for="inputDescription" class="control-label">
                        <?php echo $this->translate('Description'); ?>
                    </label>
                    <?php echo $this->formRow($tax->get('description')); ?>
                </div>

                <div class="form-group">
                    <label for="inputTerm" class="control-label">
                        <?php echo $this->translate('Type'); ?>
                    </label>
                    <?php echo $this->formRow($tax->get('term')); ?>
                </div>

                <hr class="panel-wide">

                <div class="form-group">                  
                    <?php echo $this->formRow($form->get('button')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>

    <div class="col-sm-8">

        <div class="row" style="padding-bottom: 5px">
            <div class="col-xs-6">
                <form class="form-inline">
                    <div class="form-group">
                        <select class="form-control">
                            <option >Bulk Actions</option>
                            <option value="delete">Delete</option>
                            <option value="edit">Quick Edit</option>
                        </select>
                    </div>
                    <button name="button" type="submit" class="btn btn-primary btn-small" value="appley">
                        <i class="fa fa-check"></i> &nbsp; <?php echo $this->translate('Appley'); ?>
                    </button>                
                </form>
            </div>
            <div class="col-xs-6">
                <?php
                echo $this->paginationControl(
                        $this->taxonomy, 'Sliding', 'partial/paginator.phtml', ['route' => 'post/post_category_pagintaion_edit', 'taxid' => $taxid, 'taxcount' => $taxcount, 'keyword' => $keyword]
                );
                ?>
            </div>
        </div>

        <div class="panel" style="margin-bottom: 10px">
            <div class="panel-body"> 
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                <input type="checkbox"/> 
                            </th>
                            <th><?php echo $this->translate('Title'); ?></th>
                            <th><?php echo $this->translate('Slug'); ?></th>                            
                            <th><?php echo $this->translate('Posts'); ?></th>                            
                            <th><?php echo $this->translate('Action'); ?></th>                            
                        </tr>
                    </thead>
                    <tbody> 
                        <?php foreach ($taxonomy as $cat): ?>
                            <tr>
                                <td>
                                    <input type="checkbox" value="<?php echo $cat->getId(); ?>"/> 
                                </td>                                
                                <td>
                                    <?php
                                    if (null == $keyword):
                                        for ($l = 0; $l < $cat->getLvl(); $l++) {
                                            echo "&HorizontalLine;";
                                        }
                                        if ($cat->getLvl() === 0) {
                                            echo $cat->getName();
                                        } else {
                                            echo '&nbsp;' . $cat->getName();
                                        }
                                    else:
                                        echo $cat->getName();
                                    endif;
                                    ?>
                                </td>
                                <td><?php echo $cat->getSlug(); ?></td>                                
                                <td><?php echo $cat->getCount(); ?></td>                                
                                <td>
                                    <div class="btn-group btn-group-xs">                        
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><span class="fa fa-cog"></span>&nbsp;<span class="fa fa-caret-down"></span></button>
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li>
                                                <a href="<?php echo $this->url('post/post_category_delete', ['action' => 'delete', 'id' => $cat->getId()]); ?>"><?php echo $this->translate('Delete'); ?></a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url('post/post_category_edit', ['action' => 'edit', 'id' => $cat->getId()]); ?>"><?php echo $this->translate('Edit'); ?></a>
                                            </li>      
                                            <li class="divider"></li>
                                            <li>
                                                <a href="#"><?php echo $this->translate('Quick Edit'); ?></a>
                                            </li>  
                                        </ul> 
                                    </div>
                                </td>                                
                            </tr>       
                        <?php endforeach; ?>
                    </tbody>
                </table>                
            </div>            
        </div>
        <div class="row" style="padding-bottom: 10px">
            <div class="col-xs-6">
                <form class="form-inline">
                    <div class="form-group">
                        <select class="form-control">
                            <option >Bulk Actionss</option>
                            <option value="delete">Delete</option>
                        </select>
                    </div>
                    <button name="button" type="submit" class="btn btn-primary btn-small" value="appley">
                        <i class="fa fa-check"></i> &nbsp; <?php echo $this->translate('Appley'); ?>
                    </button>  
                </form>
            </div>
            <div class="col-xs-6 ">                
                <?php
                echo $this->paginationControl(
                        $this->taxonomy, 'Sliding', 'partial/paginator.phtml', ['route' => 'post/post_category_pagintaion_edit', 'taxid' => $taxid, 'taxcount' => $taxcount, 'keyword' => $keyword]
                );
                ?>
            </div>
        </div>
        <div class="note note-info">
            <b><em><?php echo $this->translate('Note'); ?>:</em></b>
            <p><em><?php echo $this->translate('Deleting a category does not delete the posts in that category. Instead, posts that were only assigned to the deleted category are set to the category Uncategorized.'); ?></em></p>
        </div>
    </div>
    <!-- / .page-header -->
    <script>
        jQuery(function($) {
            $('ul.navigation > li > ul.submenu > li > #navigationhelper-Categories').parent().parent().parent().addClass('active open');
            $('ul.navigation > li > ul.submenu > li > #navigationhelper-Categories').parent().addClass('active');
        });
    </script>