<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try {
                ace.settings.check('breadcrumbs', 'fixed');
            } catch (e) {
            }
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="icon-home home-icon"></i>
                <a href="<?php echo $this->url('home'); ?>">
                    <?php echo $this->translate('Dashboard'); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('post'); ?>">
                    <?php echo $this->translate('Posts'); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('category'); ?>">
                    <?php echo $this->translate('Categories'); ?>
                </a>
            </li>
            <li class="active">
                <?php echo $this->translate('Edit Category'); ?>
            </li>
        </ul>
        <!-- .breadcrumb -->

        <div class="nav-search" id="nav-search">
            <form class="form-search">
                <span class="input-icon">
                    <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                    <i class="icon-search nav-search-icon"></i>
                </span>
            </form>
        </div><!-- #nav-search -->
    </div>
    <div class="page-content">
        <div class="page-header">
            <h1>
                <?php echo $this->translate('Edit Category'); ?>   
                <small>
                    <i class="icon-double-angle-right"></i>
                    <?php echo $this->translate("or"); ?> 
                    <a href="<?php echo $this->url('category',['action'=>'add']); ?>">
                        <?php echo $this->translate('Add New'); ?>
                    </a>
                </small>
            </h1>           
        </div>
         <div class="row">          
                <div class="col-xs-12">
                       content
                </div>
            </div>
    </div>
</div>

<script>
   jQuery(function ($){
        $('ul.nav > li.words').addClass('active open');
        $('ul.submenu > li.category').addClass('active');
   });   
</script>