<?php
/**
 * @var \ORM\Entity\Taxonomy $cat
 * 
 */
$i = 1;
?>
<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">
        <?php echo $this->translate('You are here:'); ?> 
    </div>
    <li>       
        <a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
    </li>
    <?php if (null == $keyword): ?>
        <li class="active">
            <?php echo $this->translate('Categories'); ?></a>
        </li>   
    <?php else: ?>
        <li>
            <a href="<?php echo $this->url('post/post_category'); ?>"><?php echo $this->translate('Categories'); ?></a>
        </li>
        <li class="active">
            <?php echo $this->translate('Keyword'); ?>
        </li>
        <li class="active">
            <?php echo $keyword; ?></a>
        </li> 
    <?php endif; ?>
</ul>
<div class="page-header">
    <div class="row">
        <div class="col-xs-6">
            <h1 class="text-center text-left-sm">
                <i class="fa fa-sitemap page-header-icon"> </i>
                &nbsp;
                <?php echo $this->translate("Categories"); ?>        
                <?php echo $this->translate('or'); ?>
                <a href="<?php echo $this->url('post/post_category_add', ['action' => 'add']); ?>"><?php echo $this->translate('Add New'); ?></a>
            </h1>
        </div>
        <div class="col-xs-6">
            <div class="pull-right" style="width: 60%">        
                <?php
                $formsearch->setAttribute('action', $this->url('post/post_category'));
                $formsearch->prepare();
                $search = $formsearch->get('search');
                $search->get('keyword')->setattributes([
                    'class' => 'form-control',
                    'placeholder' => $this->translate('Search category')
                ]);
                ?>
                <?php echo $this->form()->openTag($formsearch); ?>               
                <div class="input-group input-group-sm">
                    <?php echo $this->formHidden($formsearch->get('security')); ?>
                    <?php echo $this->formRow($search->get('keyword')); ?>
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">
                            <span class="fa fa-search"></span>
                        </button>
                    </span>
                </div>               
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div> 
<div class="row">
    <div class="col-sm-12">        
        <div class="panel colourable">
            <div class="panel-heading">
                <span class="panel-title">
                    <i class="panel-title-icon fa fa-tasks"></i>
                    <?php echo $this->translate('Categories'); ?>
                </span>
                <div class="panel-heading-controls">                    
                    <em>
                        <?php echo $this->translate('Showing 1 to'); ?> 
                        <?php echo count($this->taxonomy); ?> 
                        <?php echo $this->translate('of'); ?> 
                        <?php echo $this->taxcount; ?> 
                        <?php echo $this->translate('entries'); ?>
                    </em>
                </div>         
            </div>
            <div class="panel-body">                              
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                <input type="checkbox"/> 
                            </th>
                            <th><?php echo $this->translate('Title'); ?></th>
                            <th><?php echo $this->translate('Slug'); ?></th>                            
                            <th><?php echo $this->translate('Posts'); ?></th>                            
                            <th><?php echo $this->translate('Action'); ?></th>                            
                        </tr>
                    </thead>
                    <tbody>         

                        <?php foreach ($taxonomy as $cat): ?>
                            <tr>
                                <td>
                                    <input type="checkbox" value="<?php echo $cat->getId(); ?>"/> 
                                </td>                                
                                <td>
                                    <?php
                                    for ($l = 0; $l < $cat->getLvl(); $l++) {
                                        echo "&HorizontalLine;";
                                    }
                                    if ($cat->getLvl() === 0) {
                                        echo $cat->getName();
                                    } else {
                                        echo '&nbsp;' . $cat->getName();
                                    }
                                    ?>
                                </td>
                                <td><?php echo $cat->getSlug(); ?></td>                                
                                <td><?php echo $cat->getCount(); ?></td>                                
                                <td>                                   
                                    <div class="btn-group btn-group-xs">                        
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><span class="fa fa-cog"></span>&nbsp;<span class="fa fa-caret-down"></span></button>
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li>
                                                <a href="<?php echo $this->url('post/post_category_delete', ['action' => 'delete', 'id' => $cat->getId()]); ?>"><?php echo $this->translate('Delete'); ?></a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url('post/post_category_edit', ['action' => 'edit', 'id' => $cat->getId()]); ?>"><?php echo $this->translate('Edit'); ?></a>
                                            </li>      
                                            <li class="divider"></li>
                                            <li>
                                                <a href="#"><?php echo $this->translate('Quick Edit'); ?></a>
                                            </li>  
                                        </ul> 
                                    </div>
                                </td>                                
                            </tr>       
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="panel-footer" style="margin-top: -17px">
                <div class="row"> 
                    <?php
                    echo $this->paginationControl(
                            $this->taxonomy, 'sliding', ['partial/paginator.phtml', 'Post'], ['route' => 'post/post_category_pagintaion', 'taxcount' => $taxcount, 'keyword' => $keyword]
                    );
                    ?>
                </div>
            </div>            
        </div>
        <div class="note note-info">
            <b><em><?php echo $this->translate('Note'); ?>:</em></b>
            <p><em><?php echo $this->translate('Deleting a category does not delete the posts in that category. Instead, posts that were only assigned to the deleted category are set to the category Uncategorized.'); ?></em></p>
        </div>
    </div>

    <script>
        jQuery(function($) {
            $('ul.navigation > li > ul.submenu > li > #navigationhelper-Categories').parent().parent().parent().addClass('active open');
            $('ul.navigation > li > ul.submenu > li > #navigationhelper-Categories').parent().addClass('active');
        });
    </script>