
<!-- basic styles -->
<link href="<?php echo $this->basepath('/assets/ace/css/bootstrap.min.css'); ?>" rel="stylesheet" />
<link rel="stylesheet" href="<?php echo $this->basepath('/assets/ace/css/font-awesome.min.css'); ?>" />
<!--[if IE 7]>
	  <link rel="stylesheet" href="<?php echo $this->basepath('/assets/ace/css/font-awesome-ie7.min.css'); ?>" />
<![endif]-->
<!-- page specific plugin styles -->

<!-- fonts -->

<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

<!-- ace styles -->
<link rel="stylesheet" href="<?php echo $this->basepath('/assets/ace/css/ace.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basepath('/assets/ace/css/ace-rtl.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basepath('/assets/ace/css/ace-skins.min.css'); ?>" />

<!--[if lte IE 8]>
	  <link rel="stylesheet" href="<?php echo $this->basepath('/assets/ace/css/ace-ie.min.css'); ?>" />
<![endif]-->
