
<?php
/**
 * @var \Zend\Form\Form $this
 * @var \Post\Form\PostForm $form
 */
$this->headTitle($this->translate('Edit User'));
$this->placeholder('siteTitle')->set('PREPEND');
?>
<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">
        <?php echo $this->translate('You are here:'); ?> 
    </div>
    <li>       
        <a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
    </li>
    <li>
        <a href="<?php echo $this->url('user'); ?>"><?php echo $this->translate('Users'); ?></a>
    </li>
    <li class="active">
        <?php echo $this->translate('Edit User'); ?>
    </li>
</ul>
<div class="page-header">

    <div class="row">
        <!-- Page header, center on small screens -->
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
            <i class="fa fa-users page-header-icon"></i>
            &nbsp;&nbsp;
                <?php echo $this->translate("Edit User"); ?>
                <?php echo $this->translate("or"); ?>
            <a href="<?php echo $this->url('user/add'); ?>">
                <?php echo $this->translate("Add New"); ?>
            </a>
        </h1>
    </div>
</div> 
<!-- / .page-header -->
<div class="row">

    <div class="col-xs-12">
        <div class="panel">
            <div class="panel-heading">                 
                <span class="panel-title">
                    <i class="panel-title-icon fa fa-user"></i>
                    <?php echo $this->translate('Edit User'); ?>
                </span>
            </div>
            <div class="panel-body">
                <?php
                $form->setAttribute('action', $this->url('user/edit'));
                $form->prepare();
                echo $this->form()->openTag($form);

                $ap = $form->get("user");
//                $ap->get('commentStatus')->setOptions([
//                    "value_options" => [
//                        "E" => $this->translate("Enable"),
//                        "D" => $this->translate("Disable")
//                    ]
//                ]);
//                $ap->get('status')->setOptions([
//                    "value_options" => [
//                        "P" => $this->translate("Publish"),
//                        "D" => $this->translate("Draft")
//                    ]
//                ]);
//                $form->get('button')->setAttributes([
//                    'value' => $this->translate("Save")
//                ]);
                ?>

                <div class="form-group">
                    <label for="inputUserName" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Username'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formHidden($form->get('security')); ?>
                        <?php echo $this->formHidden($ap->get('id')); ?>
                        <?php echo $this->formRow($ap->get('userName')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputFirstName" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('First Name'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('firstName')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputLastName" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Last Name'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('lastName')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputDisplayName" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Display Name'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('displayName')); ?>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputPassword" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Password'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('password')); ?>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Email'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('email')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputQuestion" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Question'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('question')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputAnswer" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Answer'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('answer')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputRole" class="col-sm-2 control-label no-padding-right"><?php echo $this->translate('Role'); ?></label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($ap->get('role')); ?>
                    </div>
                </div>
                <hr class="panel-wide">
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-9">
                        <?php echo $this->formRow($form->get('button')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
