<?php
/**
 * @var \ORM\Entity\User $user
 */
?>
<ul class="breadcrumb breadcrumb-page">
    <div class="breadcrumb-label text-light-gray">
        <?php echo $this->translate('You are here:'); ?> 
    </div>
    <li>       
        <a href="<?php echo $this->url('dashboard'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
    </li>
    <li class="active">
        <?php echo $this->translate('Users'); ?></a>
    </li>    
</ul>
<div class="page-header">

    <div class="row">
        <!-- Page header, center on small screens -->
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
            <i class="fa fa-users page-header-icon"> </i>
            &nbsp;&nbsp;
            <?php echo $this->translate("Users"); ?>
            <?php echo $this->translate("or"); ?>
            <a href="<?php echo $this->url('user/add'); ?>"><?php echo $this->translate('Add New'); ?></a>

        </h1>
    </div>
</div> 
<!-- / .page-header -->

<div class="row">
    <div class="col-xs-12">

        <?php if (isset($users)) : ?>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('No'); ?></th>
                        <th><?php echo $this->translate('Username'); ?></th>
                        <th><?php echo $this->translate('Email'); ?></th>
                        <th><?php echo $this->translate('Role'); ?></th>
                        <th><?php echo $this->translate('Action'); ?></th>
                    </tr>
                </thead>
                <?php
                $i = 1;
                foreach ($users as $user):
                    ?>
                    <tbody>
                        <tr>
                            <td>
                                <?php echo $i++; ?>
                            </td>
                            <td>
                                <?php echo $user->getUserName(); ?>
                            </td>
                            <td>
                                <?php echo $user->getEmail(); ?>
                            </td>
                            <td>
                                <?php echo $user->getRole()->getName(); ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('user/edit', ['action' => 'edit', 'id' => $user->getId()]); ?>"><?php echo $this->translate("Edit"); ?></a>
                                | 
                                <a href="<?php echo $this->url('user/delete', ['action' => 'delete', 'id' => $user->getId()]); ?>"><?php echo $this->translate("Delete"); ?></a>
                            </td>
                        </tr>
                    </tbody>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div>
</div>



