<?php echo $this->doctype(); ?>

<!--[if IE 8]>        
    <html class="ie8"> 
<![endif]-->
<!--[if IE 9]>         
    <html class="ie9 gt-ie8"> 
<![endif]-->
<!--[if gt IE 9]><!--> 
<html class="gt-ie8 gt-ie9 not-ie"> 
    <!--<![endif]-->
    <head>
        <meta charset="utf-8">   
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

        <!-- Open Sans font from Google CDN -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">

        <!-- Pixel Admin's stylesheets -->
        <link href="<?php echo $this->basepath('/assets/PixelAdmin/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basepath('/assets/PixelAdmin/css/pixel-admin.css'); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basepath('/assets/PixelAdmin/css/widgets.css'); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basepath('/assets/PixelAdmin/css/pages.css'); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basepath('/assets/PixelAdmin/css/rtl.css'); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basepath('/assets/PixelAdmin/css/themes.css'); ?>" rel="stylesheet" type="text/css">

        <!-- Get jQuery for IE 9 -->
        <!--[if lt IE 9]>
                <script src="assets/javascripts/ie.min.js"></script>
        <![endif]-->

        <!-- Get jQuery from Google CDN -->
        <!--[if !IE]> -->
        <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">' + "<" + "/script>");</script>
        <!-- <![endif]-->
        <!--[if lte IE 9]>
                <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
        <![endif]-->

        <!-- Pixel Admin's javascripts -->
        <script src="<?php echo $this->basepath('/assets/PixelAdmin/js/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->basepath('/assets/PixelAdmin/js/pixel-admin.min.js'); ?>"></script>       

        <script>
            var init = [];            
        </script>



        <script type="text/javascript">
            init.push(function() {
                // Javascript code here
            })
            window.PixelAdmin.start(init);
        </script>

        <?php
//        echo $this->headScript()
//                ->prependFile($this->basepath('/assets/PixelAdmin/js/ie.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
//        echo $this->render('./layout/assets/css.phtml');
//        echo $this->partial('./layout/assets/head_js.phtml');
//        echo $this->headMeta()
//                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
//                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ));

        if ('SET' === $this->placeholder('siteTitle', 'APPEND')) {
            echo $this->headTitle()->setAutoEscape(false);
        } else {
            echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'), $this->placeholder('siteTitle', 'APPEND'))
                    ->setSeparator(' - ')
                    ->setAutoEscape(false);
        }
        ?>

    </head>
    <body class="theme-frost main-menu-animated">

        <!-- Demo script --> 
        <script src="<?php echo $this->basepath('/assets/PixelAdmin/js/demo.js'); ?>"></script> 
        <!-- / Demo script -->

        <div id="main-wrapper">
            <?php
            echo $this->partial('./layout/navbars.phtml');
            echo $this->partial('./layout/sidebars.phtml');
            ?>
            <div id="content-wrapper">
                <?php echo $this->content; ?>
            </div>
            <div id="main-menu-bg"></div>
        </div>





        <?php
//        echo $this->partial('./layout/sidebar.phtml');
//        echo $this->content;
//        echo $this->partial('./layout/ace_setting.phtml');
        ?>

        <?php
//        echo $this->partial('./layout/assets/end_js.phtml');
        echo $this->inlineScript()
        ?>
    </body>
</html>

