<div id="main-menu" role="navigation">
    <div id="main-menu-inner">
        <div class="menu-content top" id="menu-content-demo">           
            <div>
                <div class="text-bg"><span class="text-semibold">ozan rock</span></div>

                <img src="<?php echo $this->basepath('/assets/PixelAdmin/img/avatars/1.jpg'); ?>" alt="" class="">
                <div class="btn-group">                    
                    <a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-user"></i></a>
                    <a href="#" class="btn btn-xs btn-primary btn-outline dark"><i class="fa fa-cog"></i></a>
                    <a href="#" class="btn btn-xs btn-danger btn-outline dark"><i class="fa fa-power-off"></i></a>
                </div>
                <a href="#" class="close">&times;</a>
            </div>
        </div>
        <?php echo $this->NavigationHelper('Navigation'); ?>  
        <div class="menu-content">
           
        </div>
    </div> 
    <!-- / #main-menu-inner -->
</div> 
<!-- / #main-menu -->

