<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">   
        <?php
        echo $this->headScript()
            ->prependFile($this->basepath('/assets/ace/js/ace-extra.min.js'))
            ->prependFile($this->basepath('/assets/ace/js/html5shiv.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basepath('/assets/ace/js/respond.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basepath('/assets/ace/js/jquery-2.0.3.min.js'), 'text/javascript', array(
            'conditional' => '!IE'
        ))
            ->prependFile($this->basepath('/assets/ace/js/jquery-1.10.2.min.js'), 'text/javascript', array(
            'conditional' => 'IE'
        ));
        // ->prependFile()
        // ->prependFile();
        ?>
        <?php
        
        if ('SET' === $this->placeholder('siteTitle', 'APPEND')) {
            echo $this->headTitle()->setAutoEscape(false);
        } else {
            echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'), $this->placeholder('siteTitle', 'APPEND'))
                ->setSeparator(' - ')
                ->setAutoEscape(false);
        }
        
        echo $this->render('./layout/assets/css.phtml');
        // echo $this->partial('./layout/assets/head_js.phtml');
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ));
        ?>


    </head>
<body>
<?php
echo $this->content;
echo $this->inlineScript();
?>
</body>
</html>

