<?php
/**
 * @var \Zend\Form\Form $this
 * @var \Post\Form\PostForm $form
 */
?>
<div class="col-lg-10">
    <?php
    $form->setAttribute('action', $this->url('post', [
        'controller' => 'index',
        'action' => 'add'
    ]));
    $form->prepare();
    echo $this->form()->openTag($form);
//     $a =  new \DateTime('now');
//     echo $a->format('Y-m-d H:i:s');
    $ap = $form->get("post");
    ?>
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Title</label>
		<div class="col-sm-10">
			<?php echo $this->formHidden($form->get('security')); ?>
			<?php echo $this->formRow($ap->get('title')); ?>
		</div>
	</div>
	
	
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Content</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('content')); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Slug</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('slug')); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Staus</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('status')); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Comment Status</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('commentStatus')); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Post Status</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('postStatus')); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Parent</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('parent')); ?>
		</div>
	</div>
	
	<div class="form-group">
		<label for="inputUsername" class="col-sm-2 control-label">Account</label>
		<div class="col-sm-10">
			<?php echo $this->formRow($ap->get('account')); ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?php echo $this->formRow($form->get('button')); ?>
		</div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>