<?php
/**
 * @var \ORM\Entity\Post $post
 * @var \ORM\Entity\Post $posts
 */

$this->headTitle($this->translate('Edit Post'));
$this->placeholder('siteTitle')->set('PREPEND');
?>
<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try {
                ace.settings.check('breadcrumbs', 'fixed');
            } catch (e) {
            }
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="icon-home home-icon"></i>
                <a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('post'); ?>"><?php echo $this->translate('Posts'); ?></a>
            </li>
            <li class="active">
                <?php echo $this->translate('Edit Post'); ?>
            </li>
             <li class="active">
                <?php echo $post->getSlug(); ?>
            </li>
        </ul>
        <!-- .breadcrumb -->

        <div class="nav-search" id="nav-search">
            <form class="form-search">
                <span class="input-icon">
                    <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                    <i class="icon-search nav-search-icon"></i>
                </span>
            </form>
        </div><!-- #nav-search -->
    </div>
    <div class="page-content">
        <div class="page-header">
            <h1>
                <?php echo $this->translate('Edit Post'); ?>
                <small>
                    <i class="icon-double-angle-right"></i>
                    <?php echo $this->translate('or'); ?> <a href="<?php echo $this->url('post',['action'=>'add']); ?>"><?php echo $this->translate('Add New'); ?></a>
                </small>
            </h1>
        </div>
    </div>
</div>

<script>
   jQuery(function ($){      
        $('ul.submenu > li > a.all-post').parent().addClass('active');      
   });   
</script>