<?php
/**
 * @var \ORM\Entity\Post $post
 * @var \ORM\Entity\Post $posts
 */

$this->headTitle($this->translate('Posts'));
$this->placeholder('siteTitle')->set('PREPEND');

?>

<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
            try {
                ace.settings.check('breadcrumbs', 'fixed');
            } catch (e) {
            }
        </script>

        <ul class="breadcrumb">
            <li>
                <i class="icon-home home-icon"></i>
                <a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Dashboard'); ?></a>
            </li>
            <li class="active"><?php echo $this->translate('Posts'); ?></li>
        </ul>
        <!-- .breadcrumb -->

        <div class="nav-search" id="nav-search">
            <form class="form-search">
                <span class="input-icon">
                    <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                    <i class="icon-search nav-search-icon"></i>
                </span>
            </form>
        </div><!-- #nav-search -->
    </div>
    <div class="page-content">

        <div class="page-header">
            <h1>
                <?php echo $this->translate('Posts'); ?>
                <small>
                    <i class="icon-double-angle-right"></i>
                    <a href="<?php echo $this->url('post', ['action' => 'add']); ?>">
                        <?php echo $this->translate('Add New'); ?>
                    </a>
                </small>
            </h1>
        </div>
        <div class="row">          
            <div class="col-xs-12">
                <div class="table-responsive">
                    <?php if (isset($posts)) : ?>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th><?php echo $this->translate('No'); ?></th>
                                    <th><?php echo $this->translate('Title'); ?></th>
                                    <th><?php echo $this->translate('Content'); ?></th>
                                    <th><?php echo $this->translate('Slug'); ?></th>
                                    <th><?php echo $this->translate('Action'); ?></th>
                                </tr>
                            </thead>
                            <?php
                            $i = 1;
                            foreach ($posts as $post):
                                ?>
                                <tbody>
                                    <tr>
                                        <td><?php echo $i++; ?></td>
                                        <td><?php echo $post->getTitle(); ?></td>
                                        <td><?php echo $post->getContent(); ?></td>
                                        <td><?php echo $post->getSlug(); ?></td>
                                        <td><a
                                                href="<?php echo $this->url('post', ['action' => 'edit', 'id' => $post->getId()]); ?>"><?php echo $this->translate('Edit'); ?></a>
                                            | <a
                                                href="<?php echo $this->url('post', ['action' => 'delete', 'id' => $post->getId()]); ?>"><?php echo $this->translate('Delete'); ?></a>
                                        </td>
                                    </tr>
                                </tbody>
                            <?php endforeach; ?>
                        </table>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
   jQuery(function ($){
        $('ul.nav > li.words').addClass('active open');
        $('ul.submenu > li.all-post').addClass('active');
   });   
</script>