<?php
/**
 * @var Account\Controller\TermAccountController $this
 * @var \Account\Form\AccountForm $form
 */
$form->setAttribute ( 'action', $this->url ( 'termaccount', [
		'controller' => 'index',
		'action' => 'edit'
		] ) )->prepare ();
echo $this->form ()->openTag ( $form );
$af = $form->get ( "termaccount" );
?>
<div class="form-group">
	<label for="inputUsername" class="col-sm-2 control-label">Key</label>

	<div class="col-sm-10">
		<?php echo $this->formHidden($form->get('security')); ?>
		<?php echo $this->formHidden($af->get('id')); ?>
		<?php echo $this->formRow($af->get('termKey')); ?>
	</div>
</div>

<div class="form-group">
	<label for="inputUsername" class="col-sm-2 control-label">Value</label>
	<div class="col-sm-10">
		<?php echo $this->formRow($af->get('value')); ?>
	</div>
</div>
<div class="form-group">
	<label for="inputUsername" class="col-sm-2 control-label">AutoLoad</label>
	<div class="col-sm-10">
		<?php echo $this->formRow($af->get('autoload')); ?>
	</div>
</div>
<div class="form-group">
	<label for="inputUsername" class="col-sm-2 control-label">Account</label>
	<div class="col-sm-10">
		<?php echo $this->formRow($af->get('account')); ?>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?php echo $this->formRow($form->get('submit')); ?>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>