<?php
/**
 * @var \ORM\Entity\Account $account
 */

?>


<div>
	<div>
		<h3>Users</h3>
	</div>
	<div>
		<a href="<?php echo $this->url('termaccount',['action' => 'add']); ?>">Add Term User</a>

		<?php if (isset($termaccounts)) : ?>
			<table class="table">
				<thead>
				<tr>
					<th>No</th>
					<th>Key</th>
					<th>Value</th>
					<th>Autoload</th>
					<th>Action</th>
				</tr>
				</thead>
				<?php $i = 1; foreach ($termaccounts as $account): ?>
					<tbody>
					<tr>
						<td><?php echo $i++; ?></td>
						<td><?php echo $account->getTermKey(); ?></td>
						<td><?php echo $account->getValue(); ?></td>
						<td><?php echo $account->getAutoload(); ?></td>
						<td>
							<a href="<?php echo $this->url('termaccount', ['action' => 'edit', 'id' => $account->getId()]); ?>">Edit</a>
							|
							<a href="<?php echo $this->url('termaccount', ['action' => 'delete', 'id' => $account->getId()]); ?>">Delete</a>
						</td>
					</tr>
					</tbody>
				<?php endforeach; ?>
			</table>
		<?php endif; ?>
	</div>
</div>


