<?php
/**
 * @var \Zend\Form\Form $this
 * @var \Account\Form\AccountForm $form
 */
?>
<div class="col-lg-10">
    <?php
    $form->setAttribute('action', $this->url('account', [
                'controller' => 'index',
                'action' => 'add'
    ]));
    $form->prepare();
    echo $this->form()->openTag($form);
    $af = $form->get("account");
    ?>
    <div class="form-group">
        <label for="inputUsername" class="col-sm-2 control-label"><?php echo $this->translate('Username'); ?></label>

        <div class="col-sm-10">
            <?php echo $this->formHidden($form->get('security')); ?>
            <?php echo $this->formRow($af->get('username')); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="inputPassword" class="col-sm-2 control-label"><?php echo $this->translate('Password'); ?></label>

        <div class="col-sm-10">
            <?php echo $this->formRow($af->get('password')); ?>
        </div>
    </div>


    <div class="form-group">
        <label for="inputEmail" class="col-sm-2 control-label"><?php echo $this->translate('E-Mail'); ?></label>

        <div class="col-sm-10">
            <?php echo $this->formRow($af->get('email')); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formRow($form->get('submit')); ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>