<?php
/**
 * @var \ORM\Entity\Account $account
 */
?>


<div>
	<div>
		<h3>Users</h3>
	</div>
	<div>
		<a href="<?php echo $this->url('account',['action' => 'add']); ?>">Add
			User</a>

		<?php if (isset($accounts)) : ?>
			<table class="table">
			<thead>
				<tr>
					<th>No</th>
					<th>Username</th>
					<th>Email</th>
					<th>Action</th>
				</tr>
			</thead>
				<?php $i = 1; foreach ($accounts as $account): ?>
					<tbody>
				<tr>
					<td><?php echo $i++; ?></td>
					<td><?php echo $account->getUsername(); ?></td>
					<td><?php echo $account->getEmail(); ?></td>
					<td><a
						href="<?php echo $this->url('account', ['action' => 'edit', 'id' => $account->getId()]); ?>">Edit</a>
						| <a
						href="<?php echo $this->url('account', ['action' => 'delete', 'id' => $account->getId()]); ?>">Delete</a>
					</td>
				</tr>
			</tbody>
				<?php endforeach; ?>
			</table>
		<?php endif; ?>
	</div>
</div>


