<!-- start basic scripts -->

<script type="text/javascript">
		if("ontouchend" in document) document.write("<script src='<?php echo $this->basepath('/assets/ace/js/jquery.mobile.custom.min.js'); ?>'>"+"<"+"/script>");
</script>

<script src="<?php echo $this->basepath('/assets/ace/js/bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basepath('/assets/ace/js/typeahead-bs2.min.js'); ?>"></script>

<!-- end basic scripts -->

<!-- start page specific plugin scripts -->

<!--[if lte IE 8]>
    <script src="assets/js/excanvas.min.js"></script>
<![endif]-->

<!-- <script src="assets/js/jquery-ui-1.10.3.custom.min.js"></script> -->
<!-- <script src="assets/js/jquery.ui.touch-punch.min.js"></script> -->
<!-- <script src="assets/js/jquery.slimscroll.min.js"></script> -->
<!-- <script src="assets/js/jquery.easy-pie-chart.min.js"></script> -->
<!-- <script src="assets/js/jquery.sparkline.min.js"></script> -->
<!-- <script src="assets/js/flot/jquery.flot.min.js"></script> -->
<!-- <script src="assets/js/flot/jquery.flot.pie.min.js"></script> -->
<!-- <script src="assets/js/flot/jquery.flot.resize.min.js"></script> -->

<!-- end page specific plugin scripts -->

<!-- ace scripts -->
<script src="<?php echo $this->basepath('/assets/ace/js/ace-elements.min.js'); ?>"></script>
<script src="<?php echo $this->basepath('assets/ace/js/ace.min.js'); ?>"></script>


		