<script	src="<?php echo $this->basepath('/assets/ace/js/ace-extra.min.js'); ?>"></script>
<!--[if lt IE 9]>
    <script src="<?php echo $this->basepath('/assets/ace/js/html5shiv.js'); ?>"></script>
    <script src="<?php echo $this->basepath('/assets/ace/js/respond.min.js'); ?>"></script>
<![endif]-->

<!-- start basic scripts -->
<!--[if !IE]> -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<!-- <![endif]-->

<!--[if IE]>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]> -->
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->basepath('/assets/ace/js/jquery-2.0.3.min.js'); ?>'>" + "<" + "/script>");
</script>
<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->basepath('/assets/ace/js/jquery-1.10.2.min.js'); ?>'>"+"<"+"/script>");
</script>
<![endif]-->