<div class="pull-right ">



    <ul class="pagination" style="margin-right:-5px">
        <li class="paginate_button ">
            <a href="#" style="border: none">
                <em>
                    <?php echo $this->taxcount; ?> 
                    <?php echo $this->translate('Entries'); ?>
                </em>
            </a>
        </li>
        <?php if ($this->pageCount !== 1): ?> 
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="paginate_button ">
                    <a href="<?php echo $this->url($this->route, ['id' => $this->taxid]); ?>?<?php echo $this->keyword == null ? '' : 'keyword=' . $this->keyword . '&&'; ?>page=<?php echo $this->previous; ?>">
                        <i class="fa fa-angle-double-left"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <i class="fa fa-angle-double-left"></i>
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, ['id' => $this->taxid]); ?>?<?php echo $this->keyword == null ? '' : 'keyword=' . $this->keyword . '&&'; ?>page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, ['id' => $this->taxid]); ?>?<?php echo $this->keyword == null ? '' : 'keyword=' . $this->keyword . '&&'; ?>page=<?php echo $this->next; ?>">
                        <i class="fa fa-angle-double-right"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <i class="fa fa-angle-double-right"></i>
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
    </ul>
</div>