<div class="col-xs-6 text-left">
    <div class="btn-group btn-group-xs" >                        
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><?php echo $this->translate('Bulk action'); ?>&nbsp;<span class="fa fa-caret-down"></span></button>
        <ul class="dropdown-menu dropdown-menu-left">
            <li><a href="#"><?php echo $this->translate('Delete'); ?></a></li>
            <li><a href="#"><?php echo $this->translate('Quick Edit'); ?></a></li>                            
            <li class="divider"></li>
            <li><a href="#"><?php echo $this->translate('Check All'); ?></a></li>
            <li><a href="#"><?php echo $this->translate('Uncheck All'); ?></a></li>
        </ul> 
    </div>
</div>
<div class="col-xs-6 text-right" >
    <?php if ($this->pageCount !== 1): ?>    
        <ul class="pagination pagination-xs" style="margin-right:-6px">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="paginate_button ">
                    <a href="<?php echo $this->url($this->route, ['id' => $this->taxid]); ?>?page=<?php echo $this->previous; ?>">
                        Previous
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        Previous
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, ['id' => $this->taxid]); ?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, ['id' => $this->taxid]); ?>?page=<?php echo $this->next; ?>">
                        Next
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        Next
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    <?php endif; ?>
</div>